//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegmenterPoc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SegmenterPoc.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENTER POC.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to circle.
        /// </summary>
        public static string EffectPage_CircleLabel {
            get {
                return ResourceManager.GetString("EffectPage_CircleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flower.
        /// </summary>
        public static string EffectPage_FlowerLabel {
            get {
                return ResourceManager.GetString("EffectPage_FlowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heart.
        /// </summary>
        public static string EffectPage_HeartLabel {
            get {
                return ResourceManager.GetString("EffectPage_HeartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hexagon.
        /// </summary>
        public static string EffectPage_HexagonLabel {
            get {
                return ResourceManager.GetString("EffectPage_HexagonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string EffectPage_MaximumLabel {
            get {
                return ResourceManager.GetString("EffectPage_MaximumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string EffectPage_MinimumLabel {
            get {
                return ResourceManager.GetString("EffectPage_MinimumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string EffectPage_SaveButton {
            get {
                return ResourceManager.GetString("EffectPage_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        public static string EffectPage_SizeLabel {
            get {
                return ResourceManager.GetString("EffectPage_SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to star.
        /// </summary>
        public static string EffectPage_StarLabel {
            get {
                return ResourceManager.GetString("EffectPage_StarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick blur shape.
        /// </summary>
        public static string EffectPage_Title {
            get {
                return ResourceManager.GetString("EffectPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string SegmenterPage_AcceptButton {
            get {
                return ResourceManager.GetString("SegmenterPage_AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.
        /// </summary>
        public static string SegmenterPage_BackgroundButton {
            get {
                return ResourceManager.GetString("SegmenterPage_BackgroundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreground.
        /// </summary>
        public static string SegmenterPage_ForegroundButton {
            get {
                return ResourceManager.GetString("SegmenterPage_ForegroundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string SegmenterPage_OpenButton {
            get {
                return ResourceManager.GetString("SegmenterPage_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string SegmenterPage_ResetButton {
            get {
                return ResourceManager.GetString("SegmenterPage_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark segments.
        /// </summary>
        public static string SegmenterPage_Title {
            get {
                return ResourceManager.GetString("SegmenterPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo.
        /// </summary>
        public static string SegmenterPage_UndoButton {
            get {
                return ResourceManager.GetString("SegmenterPage_UndoButton", resourceCulture);
            }
        }
    }
}
